### ISSUE TITLE
Different styling/layout for dark theme and light theme

### ISSUE THREAD

**Issue by kahaaga** [JuliaDynamics/doctheme#4]
The light and dark themes have way different layouts/font sizes (see screenshots). Both should probably be the same? 

<img width="895" alt="Skjermbilde 2024-01-10 kl  12 07 05" src="https://github.com/JuliaDynamics/doctheme/assets/5237566/5a88b08f-973b-4bd0-911d-d6f2fb2e9f91">
<img width="935" alt="Skjermbilde 2024-01-10 kl  12 07 22" src="https://github.com/JuliaDynamics/doctheme/assets/5237566/bf9ac472-3135-4bc4-9203-ccf4e1c1a4e7">

**Comment by Datseris** [comment]
Yes, it must be because during the move to documenter v1 something changed in the way themeing is processed... But I don't know what :D 

Maybe @mortenpi knows?

**Comment by JanJereczek** [comment]
Also, the "note" box in the dark theme has dark font on dark background, which is quite inconvenient...

**Comment by Datseris** [comment]
Before moving to documenter v1, we also used to specify a different font: Montserrat. Now a different font is used. We still "attempt" to provide this font (https://github.com/JuliaDynamics/doctheme/blob/master/build_docs_with_style.jl#L43) but it is not used by the docbuild.
